### ISSUE TITLE
game.sql variables for hands

### ISSUE THREAD

**Issue by Fm5649** [Fm5649/ECE-366-Project#1]
Need to figure out how scores should be tracked in the game. My idea is to have four variables, two for each player corresponding to each hand, with a default value of 5 each.

**Comment by PawelMilewski1** [comment]
not sure if these variables are necessary. maybe these would be incorporated into the game_round.sql?


one aspect that i added to the file is changing the p1_choice and p2_choice. each turn (prefer turn than round bc turns don't necessary have a win-loss like rock/paper/scissors), would have who's turn it is, (player name), what choice they make (attack to transfer) and then the target hand (one of p1 hands or one of p2 hands) this is then displayed in history.
**this is shown below**

turn_player_name varchar(30) NOT NULL, --Which users' turn it is
player_choice varchar (50) NOT NULL, --Attack or transfer
player_target varchar(50) NOT NULL, --"P1Hand1, P1Hand1, P2Hand1, P2Hand2" 


we can also add the counts that each hand has to the history? 
this would be something like:

p1_hand1 int NOT NULL,
p1_hand2 int NOT NULL,
p2_hand1 int NOT NULL,
p2_hand2 int NOT NULL,

this would then keep a history of all the hands

**Comment by Fm5649** [comment]
That sounds good. I wasn't really sure where the best place to put the hand values was in, but I think game rounds is a fine place to put it.
For game rounds, there should also be a variable for the value of transfer or attack, like:
player_action_amount int NOT NULL

**Comment by Fm5649** [comment]
I've edited in your suggestions to the game_round.sql. If you think these changes are good, feel free to close the issue, or make another comment
