### ISSUE TITLE
game.sql (total rounds and current rounds)

### ISSUE THREAD

**Issue by PawelMilewski1** [Fm5649/ECE-366-Project#3]
game.sql currently has these two variables:
total_rounds int NOT NULL,
current_round int NOT NULL,
------------------------------
these shouldn't be really necessary. rock paper scissors had players play for a certain amount of rounds, but chopsticks should only have one game which has many turns between players. don't think we should have to count the total amount of rounds either. correct?

**Comment by PawelMilewski1** [comment]
update: 
i commented these two variables out
note: the sample_records.sql data relies on them to be commented out

**Comment by Fm5649** [comment]
I do think we should be able to track the number of turns and the current turn because we want to be able to track game history. We wouldn't be tracking rounds, but I think that tracking the number of turns would be useful.

**Comment by Fm5649** [comment]
Not necessary in game.sql because we are tracking current round in game round.sql
